### ISSUE TITLE
SmartDashboard items in Climber.java need to start with word climber

### ISSUE THREAD

**Issue by TaylerUva** [FRCTeam3255/Robot2022-V#34]
This allows them to be sorted alphabetically in Glass
https://github.com/FRCTeam3255/Robot2022-V/blob/fd03a9669f2b8ee20b599a1145a487dd4de3f88a/src/main/java/frc/robot/subsystems/Climber.java#L119-L124

`Is Climber at Minimum Switch` should be `Climber at Minimum Switch`

**Comment by IanSzalai** [comment]
closed by #47
