### ISSUE TITLE
SN_Prefernce.getValue() used in RobotContainer

### ISSUE THREAD

**Issue by TaylerUva** [FRCTeam3255/Robot2022-V#4]
These will immediatly make the value stale and never update until robot code is restarted. 

https://github.com/IanSzalai/Robot2022-V/blob/981e45c6222dab6ea0f98edd2b38f7e91854ab49/src/main/java/frc/robot/RobotContainer.java#L100-L101
https://github.com/IanSzalai/Robot2022-V/blob/981e45c6222dab6ea0f98edd2b38f7e91854ab49/src/main/java/frc/robot/RobotContainer.java#L38

**Comment by IanSzalai** [comment]
solution: get the value of the preference in `subTurret.setSpeed()`

**Comment by IanSzalai** [comment]
stale. move turret is no longer an inline command, it is now a full command due to other conditions that must be satisfied for the turret to move (ie climber)
